---
name: Secret Scan with TruffleHog

on:
  push:
  pull_request:

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Set shallow clone depth
        shell: bash
        env:
          PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "depth=$(($(jq length <<< '${{ toJson(github.event.commits) }}') + 2))" >> "$GITHUB_ENV"
            echo "branch=${{ github.ref_name }}" >> "$GITHUB_ENV"
          fi
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "depth=$((${{ github.event.pull_request.commits }}+2))" >> "$GITHUB_ENV"
            echo "branch=${PR_HEAD_REF}" >> "$GITHUB_ENV"
          fi
      - name: Checkout code with shallow clone
        uses: actions/checkout@v3
        with:
          ref: "${{ env.branch }}"
          fetch-depth: "${{ env.depth }}"
      - name: Run TruffleHog Secret Scan
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --results=verified,unknown
